/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdf9b",
        "background": "#12121d",
        "tertiary-fixed-dim": "#ecc15c",
        "on-primary-fixed-variant": "#5516be",
        "on-primary-fixed": "#23005c",
        "surface-container-lowest": "#0d0d18",
        "tertiary-container": "#896700",
        "outline": "#958e9d",
        "surface-variant": "#343440",
        "on-tertiary": "#3f2e00",
        "surface-bright": "#383845",
        "primary-fixed": "#e9ddff",
        "on-secondary-container": "#bfaddd",
        "on-tertiary-fixed-variant": "#5b4300",
        "secondary-fixed": "#ebdcff",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#f5ecff",
        "inverse-on-surface": "#302f3b",
        "primary-container": "#7c4ce6",
        "on-secondary-fixed": "#22143a",
        "on-primary": "#3c0091",
        "inverse-primary": "#6d3bd7",
        "primary": "#d0bcff",
        "error": "#ffb4ab",
        "surface-tint": "#d0bcff",
        "surface-container-low": "#1b1a26",
        "on-surface": "#e3e0f1",
        "on-background": "#e3e0f1",
        "inverse-surface": "#e3e0f1",
        "on-secondary-fixed-variant": "#4e3f68",
        "tertiary": "#ecc15c",
        "surface-container-high": "#292935",
        "on-surface-variant": "#ccc3d3",
        "on-error": "#690005",
        "secondary-container": "#4e3f68",
        "on-tertiary-container": "#ffedcc",
        "surface-dim": "#12121d",
        "secondary": "#d1beef",
        "primary-fixed-dim": "#d0bcff",
        "surface-container": "#1f1e2a",
        "outline-variant": "#4a4452",
        "on-tertiary-fixed": "#251a00",
        "on-secondary": "#372950",
        "surface-container-highest": "#343440",
        "surface": "#12121d",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#d1beef"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
